global using CatalogService.Api.Repositories;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Shared;
global using Shared.Extensions;
global using AutoMapper;
global using MassTransit;
global using System.Net;
global using FluentValidation;